### ISSUE TITLE
implement capitalized \defi* and \trefi

### ISSUE THREAD

**Issue by kohlhase** [slatex/LaTeXML-Plugin-sTeX#117]
I have introduced 
* `\Defi`, `\Defii`, `\Defiii`, `\Defiv` and `\Defis`, `\Defiis`, `\Defiiis`, `\Defivs` that capitalize their content in `statements.sty`. 
* analogously `\Mtrefi*` in `smultiling.dtx`
* analogously `\Indi*` in `omtext.dtx`.

They need to be implemented in LaTeXML as well.

**Comment by kohlhase** [comment]
@tkw1536 if you show me how to capitalize in Perl, I can do that myself.

**Comment by tkw1536** [comment]
@kohlhase Note that I am not a perl expert, but a [quick google search](http://lmgtfy.com/?q=capitalize+string+in+perl) reveals multiple ways of doing it. 

To capitalize a single word, you can use [ucfirst](https://perldoc.perl.org/functions/ucfirst.html):
```perl
print(ucfirst 'word'); # prints 'Word'
```
To capitalize all words in a sentence, you can use:
```perl
my $sentence = 'this is a sentence. ';
$sentence =~ s/(\w+)/\u$1/g;
print($sentence); # prints 'This Is A Sentence'
```

**Comment by kohlhase** [comment]
fixed on `simplify branch`
