### ISSUE TITLE
segfault with omdocpost.xsl

### ISSUE THREAD

**Issue by kohlhase** [slatex/LaTeXML-Plugin-sTeX#12]
When I convert  `prototest/smglom/foo.tex`, then I get 

```
Michaels-MBP:smglom kohlhase$ make foo.xml -B
latexmlc --profile stex-module.opt\
             --preamble pre.tex --postamble post.tex\
             --output foo.xml --log foo.xml.log\
         foo.tex 
No obvious problems
Wrote foo.xml
make: *** [foo.xml] Segmentation fault: 11
make: *** Deleting file `foo.xml'
```

but `foo.xml.log` says `no obvious problems`. 
But if I remove the line 

```
stylesheet = omdocpost.xsl
```

from `stex-module.opt` and run `cpanm` again, things work out fine. 
My suspicion is that `omdocpost.xsl` is not found. Assigning to @dginev, since I do not know how to debug. cc: @angerhang

**Comment by kohlhase** [comment]
BTW, running ```omdocpost.xsl``` manually with 
```
xsltproc ~/perl5/lib/perl5/LaTeXML/resources/XSLT/omdocpost.xsl foo.xml 
``` 
works fine.

**Comment by dginev** [comment]
Usually this is an issue with the underlying libxml and libxslt. Could you try updating those? Also, can @angerhang reproduce this? If it's mac-specific we'll be in a bind.

**Comment by kohlhase** [comment]
libxml and libxslt seem to be current with 1.1.28 and 2.9.3. 

I think that @angerhang also has a mac. 

@cmaeder, could you try to reproduce this problem on linux?

**Comment by kohlhase** [comment]
@dginev Could it be that there is something else wrong (e.g. the stylesheet is not found?) After all, ```xsltproc``` works with the style sheet, and I do not seem to have problems with regular ```latexml``` that also uses a stylesheet.

**Comment by cmaeder** [comment]
I currently have an initialization problem in `foo.xml.log`

```
Initialization complete: 4 errors; 4 missing files[ded.sty, lststex.sty, lstomdo
c.sty, calbf.sty]. Aborting.
```

```
maeder@lati:~/kwarc/LaTeXML-Plugin-sTeX/prototests/smglom$ make foo.xml -Blatexmlc --profile stex-module.opt\
         --preamble pre.tex --postamble post.tex\
         --output foo.xml --log foo.xml.log\
	 foo.tex 
Initialization failed.
Error! Did not write file foo.xml
```

**Comment by cmaeder** [comment]
I'm using LateXML from https://github.com/KWARC/LaTeXML.git

**Comment by cmaeder** [comment]
I works for me under linux (vivid) after setting STEXSTYDIR and TEXINPUTS

```
maeder@lati:~/kwarc/LaTeXML-Plugin-sTeX/prototests/smglom$ make foo.xml -Blatexmlc --profile stex-module.opt\
         --preamble pre.tex --postamble post.tex\
         --output foo.xml --log foo.xml.log\
	 foo.tex 
No obvious problems
Wrote foo.xml
```

**Comment by kohlhase** [comment]
I am not sure that you are actually using the plugin. Did you make a "local build"? Please have a look at #6 and make sure that you are testing with the local build.

**Comment by cmaeder** [comment]
I made a `cpanm .` in LaTeXML-Plugin-sTeX but use `latexmlc` from my old installation.

**Comment by cmaeder** [comment]
Right, the profile is loaded from `/var/data/localmh/ext/LaTeXML/blib/lib/LaTeXML/resources/Profiles/stex-module.opt...`

**Comment by kohlhase** [comment]
yes, that is not what we want to test.

**Comment by cmaeder** [comment]
`cpanm .` made nothing, so I supposed the LaTeXML dependency was fine. How do I convince latexml to use LaTeXML-Plugin-sTeX/lib/LaTeXML/resources/Profiles or force reinstallation of LaTeXML?

**Comment by kohlhase** [comment]
I am not quite sure, I was quite brutal in doing this: I removed all old versions of LaTeXML I could find and, did the "local stuff" from #6  then redid the
```
perl Makefile.PL;make;make install
``` 
there is probably a better way, but I do not quite know what it is. 
You could also try on a virgin machine.

**Comment by cmaeder** [comment]
Ok, my PERL5LIB was wrongly set to `/var/data/localmh/ext/LaTeXML/blib/lib`. If I set it to `/var/data/localmh/ext/perl5lib/lib/perl5` it picks up the newly installed stuff of LaTeXML-Plugin-sTeX.

I've also set `export PERL_CPANM_OPT=--local-lib=/var/data/localmh/ext/perl5lib`.

The example now works fine without TEXINPUTS and STEXSTYDIR set:

```
maeder@lati:~/kwarc/LaTeXML-Plugin-sTeX/prototests/smglom$ make foo.xml -Blatexmlc --profile stex-module.opt\
         --preamble pre.tex --postamble post.tex\
         --output foo.xml --log foo.xml.log\
	 foo.tex 
No obvious problems
Wrote foo.xml
```

**Comment by kohlhase** [comment]
OK, that is already good. But I just see that in ```lib/LaTeXML/resources/profiles/stex-module.opt```, the line with ```stylesheet=....``` is still commented out. Could you please change that, reinstall (```cpanm .```) and then test again?

**Comment by kohlhase** [comment]
> If it's mac-specific we'll be in a bind.

@dginev, no we would not really be in a bind, since at KWARC, we would mostly be using the plugin as part of LMH docker, where it runs under (virtual) linux (once we have integrated it; see #10).

**Comment by cmaeder** [comment]
I have `libxslt.so.1.1.28` and `libxml2.so.2.9.2`

**Comment by kohlhase** [comment]
yes, but does it still work after you turn on the stylesheet?

**Comment by cmaeder** [comment]
Sorry, I was distracted. A line `stylesheet=` is entirely missing.

**Comment by cmaeder** [comment]
Sorry again, only looked into `stexml-module.opt`

**Comment by cmaeder** [comment]
works, too

```
...
Conversion complete: No obvious problems.

(post-processing...
(Scan foo.xml processing... 0.00 sec)
(CrossRef foo.xml processing... 0.00 sec)
(XSLT[using omdocpost.xsl] foo.xml processing... 0.00 sec)
(Writer foo.xml processing... 0.00 sec) 0.00 sec)
Post-processing complete: No obvious problems
processing finished Thu Jan 14 12:11:50 2016
Status:conversion:0
```

**Comment by kohlhase** [comment]
can you commit the generated XML, then I can have a look.

**Comment by cmaeder** [comment]
done (but .gitignore may hide it)

**Comment by kohlhase** [comment]
could you please also try making ```foo.en.xml```? Just to be sure.

**Comment by cmaeder** [comment]
done

**Comment by kohlhase** [comment]
thanks. I have tried this now (there was still an error in ```foo.en.tex``` and now I cannot reproduce the segfault any more. Closing. Thanks for all the help.

**Comment by cmaeder** [comment]
should `stex-module.opt` be committed with `stylesheet = omdocpost.xsl`?

**Comment by kohlhase** [comment]
Ah, now I see that I had tested without the stylesheet, dang still gives me a segfault.

**Comment by kohlhase** [comment]
I just committed. \

**Comment by angerhang** [comment]
`omdocpost.xsl` is found by by latexmlc. If we try to preload something that doesn't exist, it will throw a file not found error:
```
Math parsing succeeded:
   ltx:XMath: 1/1
 0.00 sec)
(Finalizing... 0.00 sec)
Conversion complete: No obvious problems.

Error:missing-file:tests.xsl No stylesheet 'tests.xsl' found!
```

The interesting bit is that if we only include the sTeX specific stysheet and throw away all of these 
```
<!-- old <xsl:include href="graphics.xsl"/>, replaced by LaTeXML treatment -->
<!-- old <xsl:include href="listings.xsl"/>, replaced by LaTeXML treatment -->
<xsl:include href="LaTeXML-common.xsl"/>
<xsl:include href="LaTeXML-misc-xhtml.xsl"/>
<xsl:include href="LaTeXML-inline-xhtml.xsl"/>
<xsl:include href="LaTeXML-block-xhtml.xsl"/>
<xsl:include href="LaTeXML-para-xhtml.xsl"/>
<xsl:include href="LaTeXML-tabular-xhtml.xsl"/>
<xsl:include href="LaTeXML-picture-xhtml.xsl"/>
<xsl:include href="LaTeXML-structure-xhtml.xsl"/>
<xsl:include href="LaTeXML-bib-xhtml.xsl"/>
```
we can run successfully without the segmentation fault. 

Perhaps these stysheet are already preloaded when `latexmlc` starts? @dginev can comment on this?
So including them the second time might be the actual cause of the problem.

**Comment by kohlhase** [comment]
No, this sounds like a catalog error, I have the feeling that it does not find the LaTeXML stylesheets. @dginev, do you have an idea?

**Comment by kohlhase** [comment]
this seems mac-specific. Let's hope for the best.

**Comment by dginev** [comment]
I would like to see the trace of the segfault. XSLT stylesheets should be completely safe to reload btw.

I would also need to check the versions of your libxml, libxslt, XML::LibXML and XML::LibXSLT

**Comment by kohlhase** [comment]
I think this went away somehow.
