### ISSUE TITLE
Weird bug with \guse in \inlineex

### ISSUE THREAD

**Issue by Jazzpirate** [slatex/LaTeXML-Plugin-sTeX#131]
Occurs in https://gl.mathhub.info/smglom/mv/blob/master/source/mv.en.tex#L6

This causes an `Error:malformed:ltx:text Attempt to close </ltx:text>, which isn't open`. The `ltx:txt` is opened (and closed) by `\inlineex`.

The problem is solved by putting the `\guse` command **in front of** the `\inlineex`. It's unclear to me whether this is malformed stex or a bug in the bindings, the latter look straight-forward to me, and the fact that they do work properly when used separately makes it difficult for me to debug.

**Comment by kohlhase** [comment]
That is not so weird, this is probably a schema error, that the result XML of \guse is not allowed in `<ltx:text>`, but outside, so it tries to auto-close. I will have to look at this, but do not have time at the moment.

**Comment by kohlhase** [comment]
Oh, yes, and the `\guse` is exactly where it should be.

**Comment by kohlhase** [comment]
It turned out that the OMDoc schema forgot to allow the `<omdoc:use>` in the Inline Class. I have fixed this, and I hope that this will fix this issue as well. Please try again. You will need to build the schema.

**Comment by Jazzpirate** [comment]
`Error:malformed:ltx:tags <ltx:tags> isn't allowed in <ltx:item>
	at mv.de.tex; line 5 col 15 - line 5 col 15`
...is that an issue with the xml scheme as well?

**Comment by kohlhase** [comment]
sounds very much like it. I will have a look.

**Comment by kohlhase** [comment]
Yes, turned out to be a schema error. Pushed a fix.
