### ISSUE TITLE
Defi, Trefi and friends (capitalization)

### ISSUE THREAD

**Issue by Jazzpirate** [slatex/LaTeXML-Plugin-sTeX#133]
For `defi`, `defii`, `defis` etc. (and analogously for `trefi` variants) exist capitalized versions (`Defi`, `Defii`,...) that are supposed to capitalize the concept name (without capitalizing the *symbol*-name).

No LaTeXML bindings for those exist yet, and I have no idea how to implement their functionality. Ideally, this should be done without separate bindings for each variant, I guess.

**Comment by kohlhase** [comment]
All these are variants of  `\defi` and `\trefi` are implemented using the `\definiendum` and `\termref`. They are syntactic sugar really. Ideally, we could just `RawTeX` the first macros and only rely on native implementations of the latter. 
@tkw1536

**Comment by kohlhase** [comment]
I believe that this is fixed on the `redefi` branch.
