### ISSUE TITLE
multiple defis in a definition

### ISSUE THREAD

**Issue by Jazzpirate** [slatex/LaTeXML-Plugin-sTeX#134]
...yields `Info:malformed:id Duplicated attribute xml:id`

Example: https://gl.mathhub.info/smglom/algebra/blob/master/source/quotient-group.de.tex
here, quotient-group is "defined" twice, since in german there are two common names for it (in line 10).

This seems to casuse the bindings to attempt to generate the same symbol with the same id twice. The relevant code is here: https://github.com/slatex/LaTeXML-Plugin-sTeX/blob/master/lib/LaTeXML/Package/statements.sty.ltxml#L199

What *should* happen is probably a check whether a symbol already exists before the corresponding `<omdoc:symbol>` node is generated, but I don't know enough perl to do that other than seriously hacky.

**Comment by kohlhase** [comment]
Actually, I think will not be able to do this only my own, but will need help from Deyan and/or Tom. But I have verified that Dennis' description seems to be a correct analysis of the problem.

**Comment by Jazzpirate** [comment]
solved locally; will do a PR once all bugfixes are done

**Comment by Jazzpirate** [comment]
fixed with db806707952b801edd2e1b4987b9747e8f3ad87c
