### ISSUE TITLE
rebase LaTeXMLsTeX on LaTeXML master

### ISSUE THREAD

**Issue by kohlhase** [slatex/LaTeXML-Plugin-sTeX#76]
@dginev suggests to just replace the KWARC branch in LaTeXMLsTeX with Bruce's master and see what breaks. @angerhang should do the experiment. Maybe breakage is not so bad.

**Comment by dginev** [comment]
Back in my time at NIST we managed to reintegrate most of the major differences with the main repository (e.g. including the daemon and some of the high level classes).

The main remaining differences should be:
 - Locator information (in ```stex:srcref``` attributes) depends on a slightly modified locator syntax that we have added to the KWARC/LaTeXML fork. There may be an easy way to work around it, or to provide it from master.
 - There are some enhancements to the OpenMath generation that may not have swam up to the main repository yet, so we should keep an eye open for them.

An example workflow would be to backup several OMDoc files from sTeX (e.g. my favourite sets-introduction and sets-operations) and regenerate them using the master latexml branch. That may fail, or it may succeed with an informative diff from the original, which would be a good point to analyze the differences and come up with a reintegration strategy.

**Comment by kohlhase** [comment]
@angerhang, this has priority now, the KWARC branch is no longer updated and becomes more and more obsolete. If you need to talk to me about this, just come by my office until 14:00 today.

**Comment by kohlhase** [comment]
In particular, fixes like the one Bruce just did with OMATTR will not reach the KWARC branch.

**Comment by angerhang** [comment]
Both `LaTeXML-Plugin-sTeX` and `KWARC/LaTeXML` have a `sync` branch which we should use for integration purposes.

**Comment by angerhang** [comment]
I did an orphan checkout for `LaTeXML` and cloned everything from Bruce's fork. The files we have in the `sync` branch are identical to the upstream. It is just the file modes are being changed. I hope that won't cause any problem in the future merging.

**Comment by kohlhase** [comment]
I am not sure I understand this. Did you run any tests?

**Comment by angerhang** [comment]
Yes Deyan is right. The `stex:srcref` yields different results. In `MathHub/smglom/mv/source`

For the original omdoc generated by the KWARC fork, we get
```xml
<?xml version="1.0"?>
<!--This OMDoc document is generated from an sTeX-encoded one via LaTeXML, you
  may want to reconsider editing it.-->
<omdoc xmlns:omdoc="http://omdoc.org/ns" xmlns="http://omdoc.org/ns" xmlns:stex="http://kwarc.info/ns/sTeX" xmlns:dc="http://purl.org/dc/elements/1.1/" xml:base="https://mathhub.info" xml:id="omdoc1" about="#omdoc1" stex:srcref="smglom/mv/source/structure.en.tex#textrange(from=5;0,to=0;0)">
  <omdoc:theory xml:id="structure.en" about="#structure.en" stex:srcref="smglom/mv/source/structure.en.tex#textrange(from=1;0,to=7;13)">
    <omdoc:metadata xml:id="structure.en.metadata1" about="#structure.en.metadata1" stex:srcref="smglom/mv/source/structure.en.tex#textrange(from=1;0,to=7;13)">
      <dc:creator xml:id="structure.en.metadata1.creator1" about="#structure.en.metadata1.creator1" stex:srcref="smglom/mv/source/structure.en.tex#textrange(from=1;0,to=7;13)">miko</dc:creator>
    </omdoc:metadata>
    <omdoc:imports from="smglom/mv/source/structure#structure" xml:id="structure.en.imports2" about="#structure.en.imports2" stex:srcref="smglom/mv/source/structure.en.tex#textrange(from=1;0,to=7;13)"/>
    <omdoc:symbol name="structure" xml:id="structure.def.sym" about="#structure.def.sym" stex:srcref="smglom/mv/source/structure.en.tex#textrange(from=2;1,to=6;16)"/>
```

and for the upstream we get 
```xml
<?xml version="1.0"?>
<!--This OMDoc document is generated from an sTeX-encoded one via LaTeXML, you
  may want to reconsider editing it.-->
<omdoc xmlns:omdoc="http://omdoc.org/ns" xmlns="http://omdoc.org/ns" xmlns:stex="http://kwarc.info/ns/sTeX" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:om="http://www.openmath.org/OpenMath" xmlns:m="http://www.w3.org/1998/Math/MathML" xml:base="https://mathhub.info" xml:id="omdoc1" about="#omdoc1" stex:srcref="at /Users/Hang/lmh/localmh/MathHub/smglom/meta-inf/lib/pre.en.tex; line 5 col 16">
  <omdoc:theory xml:id="equal.en" about="#equal.en" stex:srcref="at /Users/Hang/lmh/localmh/MathHub/smglom/mv/source/equal.en.tex; line 1 col 41">
    <omdoc:imports from="smglom/numberfields/source/arithmetics#arithmetics"/>
    <omdoc:metadata xml:id="equal.en.metadata1" about="#equal.en.metadata1" stex:srcref="at /Users/Hang/lmh/localmh/MathHub/smglom/mv/source/equal.en.tex; line 1 col 41">
      <dc:creator xml:id="equal.en.metadata1.creator1" about="#equal.en.metadata1.creator1" stex:srcref="at /Users/Hang/lmh/localmh/MathHub/smglom/mv/source/equal.en.tex; line 1 col 41">miko</dc:creator>
    </omdoc:metadata>
    <omdoc:imports from="smglom/mv/source/equal#equal" xml:id="equal.en.imports2" about="#equal.en.imports2" stex:srcref="at /Users/Hang/lmh/localmh/MathHub/smglom/mv/source/equal.en.tex; line 1 col 41"/>
    <omdoc:symbol name="equal" xml:id="equal.def.sym" about="#equal.def.sym" stex:srcref="at /Users/Hang/lmh/localmh/MathHub/smglom/mv/source/equal.en.tex; line 2 col 19"/>
```

What exactly do we want for the rebasing, do we want to keep the locator from the upstream or do something different?

**Comment by kohlhase** [comment]
this is done.
